### ISSUE TITLE
help: Typecheck fails after updating to v5.3.0 at `NitroRouteConfig`

### ISSUE THREAD

**Issue by dredav** [nuxt-modules/robots#221]
### 📚 What are you trying to do?

First of all: Thanks for creating and maintaining this Nuxt module!

After updating some of the dependencies in our Nuxt project (we're using Nuxt v3), we encountered some type-checking errors when running `nuxt typecheck`. We traced the issue to the `@nuxtjs/robots` dependency, the errors started appearing after upgrading from version `@5.2.11` to `@5.3.0`.

```
nuxt.config.ts:185:9 - error TS2353: Object literal may only specify known properties, and 'ssr' does not exist in type 'NitroRouteConfig'.

185         ssr: false,
            ~~~
```

We defined the SSR pages as documented in the Nuxt documentation [here](https://nuxt.com/docs/3.x/guide/concepts/rendering#route-rules):
```
  nitro: {
    routeRules: {
      '/books/**': { ssr: true },
    },
  },

```

### ℹ️ Additional context

Downgrading the package to `@5.2.11` works for now, but I'm quite sure this type change wasn't intended in `@5.3.0`.
